/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "on-tertiary-container": "#98805d",
        "surface-dim": "#dcd9db",
        "on-surface": "#1b1b1d",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#574425",
        "on-secondary-fixed": "#001e2c",
        "inverse-primary": "#bec6e0",
        "on-background": "#1b1b1d",
        "inverse-on-surface": "#f3f0f2",
        "surface-bright": "#fcf8fa",
        primary: "#000000",
        background: "#fcf8fa",
        "tertiary-fixed": "#fcdeb5",
        "on-tertiary-fixed": "#271901",
        "inverse-surface": "#303032",
        "surface-container-highest": "#e4e2e4",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#c4e7ff",
        "on-secondary": "#ffffff",
        tertiary: "#000000",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed-dim": "#7bd0ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        outline: "#76777d",
        "surface-container-high": "#eae7e9",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#004d6a",
        "tertiary-container": "#271901",
        surface: "#fcf8fa",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-low": "#f6f3f5",
        secondary: "#00668a",
        error: "#ba1a1a",
        "primary-container": "#131b2e",
        "surface-variant": "#e4e2e4",
        "surface-container": "#f0edef",
        "tertiary-fixed-dim": "#dec29a",
        "secondary-container": "#40c2fd",
        "on-secondary-fixed-variant": "#004c69",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        base: "8px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "stack-sm": "12px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        hanken: ["Hanken Grotesk", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
